global:
  scrape_interval: 10s     # Balanced for performance and real-time updates
  evaluation_interval: 10s  # Match scrape interval for consistency
  external_labels:
    monitor: 'llm-inference-server'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'llm-inference-server'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 10s  # Balanced for performance and real-time updates
    scrape_timeout: 5s    # Adjusted timeout accordingly
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']